const icons = {
  apple: "./icon-apple.png",
  bootstrap: "./icon-bootstrap.png",
  c: "./icon-c.png",
  css: "./icon-css.png",
  figma: "./icon-figma.png",
  firebase: "./icon-firebase.png",
  git: "./icon-git.png",
  html: "./icon-html.png",
  jquery: "./icon-jquery.png",
  js: "./icon-js.png",
  nextjs: "./icon-nextjs.png",
  react: "./icon-react.png",
  reactquery: "./icon-reactquery.png",
  reactrouter: "./icon-reactrouter.png",
  recoil: "./icon-recoil.png",
  redux: "./icon-redux.png",
  scss: "./icon-scss.png",
  styledcomponents: "./icon-styledcomponents.png",
  tailwind: "./icon-tailwind.png",
  ts: "./icon-ts.png",
  windows: "./icon-windows.png",
};

export default icons;
